name: CI

on: [create]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Run
      env:
        SEMAPHORECI_TOKEN: ${{ secrets.SEMAPHORECI_TOKEN }}
      run: docker run --rm -e SEMAPHORECI_TOKEN  mmatur/run-semaphoreci-build:v1.1.1 --owner=containous --project=traefikee --tagevent
